# Datasource BaseSetting
server:
  port: 9191
  contextPath: /multipledbs

my.datasource.abstract:
    driverClassName: com.mysql.jdbc.Driver
    sqlScriptEncoding: UTF-8
    # pooling
    maxActive: 15
    maxIdle: 10
    minIdle: 5
    initialSize: 2
    # Re-connect
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 600000
# datasource1
datasource.db1:
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: root
# datasource2
datasource.db2:
    url: jdbc:mysql://localhost:3306/db2
    username: root
    password: root